<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTs7fjhm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTs7fjhm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTs7fjhm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTs7fjhm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTs7fjhm\appProdProjectContainer([
    'container.build_hash' => 'Ts7fjhm',
    'container.build_id' => 'afbb0486',
    'container.build_time' => 1666551157,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTs7fjhm');
